export enum ActionTypes {
  USER_LOGINS_CREDENTIALS_CREATE = 'muttaqi/user/USER_LOGINS_CREDENTIALS_CREATE',
  USER_LOGINS_CREDENTIALS_UPDATE = 'muttaqi/user/USER_LOGINS_CREDENTIALS_UPDATE',
  USER_LOGINS_CREDENTIALS_DELETE = 'muttaqi/user/USER_LOGINS_CREDENTIALS_DELETE',
  USER_SECURE_NOTES_CREATE = 'muttaqi/user/USER_SECURE_NOTES_CREATE',
  USER_SECURE_NOTES_UPDATE = 'muttaqi/user/USER_SECURE_NOTES_UPDATE',
  USER_SECURE_NOTES_DELETE = 'muttaqi/user/USER_SECURE_NOTES_DELETE',
}
