// enum
export enum ActionTypes {
  USER_LOCATION = 'muttaqi/login/USER_LOCATION',
  USER_SIGN_UP_INFO_SCUCESS = 'muttaqi/user/USER_SIGN_UP_INFO_SCUCESS',
  USER_SIGN_IN_INFO_SCUCESS = 'muttaqi/user/USER_SIGN_IN_INFO_SCUCESS',
  USER_LOGINS_CREDENTIALS_CREATE = 'muttaqi/user/USER_LOGINS_CREDENTIALS_CREATE',
  USER_LOGINS_CREDENTIALS_UPDATE = 'muttaqi/user/USER_LOGINS_CREDENTIALS_UPDATE',
  USER_LOGINS_CREDENTIALS_DELETE = 'muttaqi/user/USER_LOGINS_CREDENTIALS_DELETE',
}
